### ISSUE TITLE
Wrong path in Debian package

### ISSUE THREAD

**Issue by jonasob** [ether/pad#205] opened 2010-12-09 08:15 UTC
The Debian package for Etherpad has in its /etc/init.d/etherpad the DAEMON_BASE /usr/local/etherpad whereas the package contains etherpad in /usr/share/etherpad. A simple replace fixes that and makes etherpad start :-)

We discovered this while installing http://pad.ffkp.se/

**Comment by brother** [comment] 2011-02-10 00:02
duplicate of 195, please close this one.

**Comment by sesam** [comment] 2011-05-14 09:58
Duplicate of #195

**Closed as completed by sesam** 2011-05-14 09:58 UTC
