### ISSUE TITLE
missing templates (still valid?)

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#116] opened 2010-07-04 13:06 UTC
net.appjet.bodylock.JSRuntimeException:  Error while executing: Not a file: undefined (module fileutils.js#31)

**Comment by holtzermann17** [comment] 2010-07-04 13:07
Also observed: Error while executing: null

**Comment by holtzermann17** [comment] 2010-07-04 13:45
Can we have some more info about just how to reproduce?

**Comment by Koschi** [comment] 2010-08-06 17:30
Got the same error here.
Installed on debian lenny using the official etherpad deb-repository. Had to use the Sid repository for scala though, since there is no scala package for Lenny.

I did not change anything except for the database and domain config. Useraccounts have been created by the package.

Here's the complete trace:

net.appjet.bodylock.JSRuntimeException: Error while executing: Not a file: undefined (module fileutils.js#31)
at net.appjet.bodylock.InnerExecutable.execute(bodylock.scala:84)
        at net.appjet.oui.execution$$anonfun$execute$4.apply(execution.scala:508)
        at net.appjet.oui.NoninheritedDynamicVariable.withValue(dynamicvar.scala:38)
        at net.appjet.oui.ExecutionContextUtils$.withContext(execution.scala:334)
        at net.appjet.oui.execution$.execute(execution.scala:504)
        at net.appjet.oui.execution$.execute(execution.scala:483)
        at net.appjet.oui.OuiServlet.execute(execution.scala:413)
        at net.appjet.oui.OuiServlet.doGet(execution.scala:360)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:502)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.handler.HandlerList.handle(HandlerList.java:49)
        at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:536)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:913)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:539)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:405)
        at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
        at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Caused by: org.mozilla.javascript.JavaScriptException: Not a file: undefined (module fileutils.js#31)
        at JS$module$fileutils$js$24._c1(module fileutils.js:31)
        at JS$module$fileutils$js$24.call(module fileutils.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
        at JS$module$fileutils$js$24._c2(module fileutils.js:37)
        at JS$module$fileutils$js$24.call(module fileutils.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
        at JS$module$etherpad$utils$js$30._c10(module etherpad/utils.js:132)
        at JS$module$etherpad$utils$js$30.call(module etherpad/utils.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
        at JS$module$etherpad$control$pro$admin$pro$admin$control$js$77._c8(module etherpad/control/pro/admin/pro_admin_control.js:118)
        at JS$module$etherpad$control$pro$admin$pro$admin$control$js$77.call(module etherpad/control/pro/admin/pro_admin_control.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:108)
        at JS$pro$admin$admin$template$ejs$285._c1(pro/admin/admin-template.ejs:25)
        at JS$pro$admin$admin$template$ejs$285.call(pro/admin/admin-template.ejs)
        at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2348)
        at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:272)
        at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:127)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:86)
        at JS$module$ejs$js$11._c22(module ejs.js:395)
        at JS$module$ejs$js$11.call(module ejs.js)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
        at JS$module$etherpad$utils$js$30._c10(module etherpad/utils.js:139)
        at JS$module$etherpad$utils$js$30.call(module etherpad/utils.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
        at JS$module$etherpad$utils$js$30._c16(module etherpad/utils.js:185)
        at JS$module$etherpad$utils$js$30.call(module etherpad/utils.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:108)
        at JS$framed$framedpage$pro$ejs$283._c1(framed/framedpage-pro.ejs:28)
        at JS$framed$framedpage$pro$ejs$283.call(framed/framedpage-pro.ejs)
        at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2348)
        at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:272)
        at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:127)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:86)
        at JS$module$ejs$js$11._c22(module ejs.js:395)
        at JS$module$ejs$js$11.call(module ejs.js)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
        at JS$module$etherpad$utils$js$30._c10(module etherpad/utils.js:139)
        at JS$module$etherpad$utils$js$30.call(module etherpad/utils.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
        at JS$module$etherpad$utils$js$30._c12(module etherpad/utils.js:151)
        at JS$module$etherpad$utils$js$30.call(module etherpad/utils.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
        at JS$module$etherpad$utils$js$30._c13(module etherpad/utils.js:174)
        at JS$module$etherpad$utils$js$30.call(module etherpad/utils.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
        at JS$module$etherpad$utils$js$30._c15(module etherpad/utils.js:187)
        at JS$module$etherpad$utils$js$30.call(module etherpad/utils.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
        at JS$module$etherpad$control$pro$admin$pro$admin$control$js$77._c7(module etherpad/control/pro/admin/pro_admin_control.js:121)
        at JS$module$etherpad$control$pro$admin$pro$admin$control$js$77.call(module etherpad/control/pro/admin/pro_admin_control.js)
        at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
        at JS$module$etherpad$control$pro$admin$pro$config$control$js$92._c3(module etherpad/control/pro/admin/pro_config_control.js:40)
        at JS$module$etherpad$control$pro$admin$pro$config$control$js$92.call(module etherpad/control/pro/admin/pro_config_control.js)
        at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:57)
        at JS$module$dispatch$js$9._c11(module dispatch.js:139)
        at JS$module$dispatch$js$9.call(module dispatch.js)
        at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2348)
        at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:272)
        at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:127)
        at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
        at JS$module$dispatch$js$9._c9(module dispatch.js:96)
        at JS$module$dispatch$js$9.call(module dispatch.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
        at JS$module$etherpad$control$pro$admin$pro$admin$control$js$77._c9(module etherpad/control/pro/admin/pro_admin_control.js:139)
        at JS$module$etherpad$control$pro$admin$pro$admin$control$js$77.call(module etherpad/control/pro/admin/pro_admin_control.js)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
        at JS$module$dispatch$js$9._c11(module dispatch.js:123)
        at JS$module$dispatch$js$9.call(module dispatch.js)
        at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2348)
        at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:272)
        at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:127)
        at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
        at JS$module$dispatch$js$9._c9(module dispatch.js:96)
        at JS$module$dispatch$js$9.call(module dispatch.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
        at JS$module$etherpad$control$pro$pro$main$control$js$73._c1(module etherpad/control/pro/pro_main_control.js:49)
        at JS$module$etherpad$control$pro$pro$main$control$js$73.call(module etherpad/control/pro/pro_main_control.js)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
        at JS$module$dispatch$js$9._c11(module dispatch.js:123)
        at JS$module$dispatch$js$9.call(module dispatch.js)
        at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2348)
        at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:272)
        at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:127)
        at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
        at JS$module$dispatch$js$9._c9(module dispatch.js:96)
        at JS$module$dispatch$js$9.call(module dispatch.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
        at JS$module$main$js$8._c24(module main.js:423)
        at JS$module$main$js$8.call(module main.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:108)
        at JS$module$main$js$8._c5(module main.js:125)
        at JS$module$main$js$8.call(module main.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
        at JS$module$onrequest$js$195._c0(module onrequest.js:24)
        at JS$module$onrequest$js$195.call(module onrequest.js)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:401)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3004)
        at JS$module$onrequest$js$195.call(module onrequest.js)
        at JS$module$onrequest$js$195.exec(module onrequest.js)
        at net.appjet.bodylock.InnerExecutable$$anonfun$execute$1.apply(bodylock.scala:76)
        at net.appjet.bodylock.InnerExecutable$$anonfun$execute$1.apply(bodylock.scala:75)
        at net.appjet.bodylock.BodyLock$.runInContext(bodylock.scala:111)
        at net.appjet.bodylock.InnerExecutable.execute(bodylock.scala:75)
        ... 23 more

Hope this helps.

**Comment by Koschi** [comment] 2010-08-06 17:34
BTW: The error occurs when accessing some of the administrative functions.
e.g.: Usage Stats, Pad Inspector -> Snoop, Plugin Manager
Didn't test everything.

If I can help you with something, just ask.

**Comment by jschneider** [comment] 2010-08-18 12:41
Same here. Fresh install using the deb repository on a fresh Ubuntu 10.04 i386 VM.
Several of the admin actions trigger that error...

**Comment by mikyter** [comment] 2010-08-28 17:00
Fixed the "Not a file: undefined" bug (see http://github.com/mikyter/pad). Etherpad was looking for a missing template.

**Comment by sesam** [comment] 2011-02-02 21:50
Fixed with commit https://github.com/ether/pad/commit/74e059a20b3b4788021a55d1522bdcd4b29ee2df

**Closed as completed** 2011-02-03 05:50 UTC
Labels: Bugs

**Comment by sesam** [comment] 2011-02-23 00:28
Note, before pushing a new version release, https://github.com/ether/pad/commit/15f8474031ca0866973b74d8bd4af656a87fadb2#commitcomment-280208
