### ISSUE TITLE
Etherpad sporadically inserts double spaces instead of single spaces

### ISSUE THREAD

**Issue by ilpssun** [ether/pad#277] opened 2011-06-20 13:40 UTC
While writing on a rather large pad, I noticed that some single space gaps between words are sporadically converted to two spaces by etherpad.  I haven’t figured out yet how to reproduce the phenomenon, but it’s happening all over the text.  I haven’t actually seen any double spaces appear while editing, either, but I’m noticing double spaces in proof-reading/editing passages I haven't touched a while and I'm certain that I didn’t enter two spaces in places where there are two now. 

Running Etherpad 1.1 using Firefox 4 and Chrome 12

**Comment by redhog** [comment] 2011-07-14 09:22
This is a bug in copy-pasting text I think

**Comment by mcnair** [comment] 2012-02-06 03:38
i have this same problem in firefox 10.0 and Chrome. It is a copy and paste issue for me. Even when copying and pasting from within the same pad extra spaces are created. It wasnt bothering me that much, but i worked with a copy editor and she has sworn off etherpad till this problem is fixed. It can be pretty frustrating, and doesnt appear to be a problem with conversion from word, or other text editors as is first suspected. hope this gets bumped up the priority list. thanks!

**Comment by jo-tud** [comment] 2012-03-16 10:46
We also have this problem - it can get very annoying when it irritates you during the writing process... I keep removing the double spaces when re-reading my text even though I know search&replace would be a work-around.
Please fix!

**Comment by objarni** [comment] 2012-10-30 08:04
Is anybody working on this bug..? It's been in Etherpad since I learned about the software, like 2009 or something ;)

**Comment by JohnMcLear** [comment] 2012-10-30 10:18
Nop

Olof Bjarnason notifications@github.com wrote:

Is anybody working on this bug..? It's been in Etherpad since I learned about the software, like 2009 or something ;)

---

**Comment by objarni** [comment] 2012-10-30 10:30
I guess a strategy would to just remove "double spaces" replace('  ', ' ') after a paste? How often do you actually want doublespaces in text on paste? (if you do want it, like on a monospaced pad, you could have an option to turn of "cleanup" on paste).

How hard is it to setup an Ubuntu computer with a local Etherpad instance? I might work on this bug if it's not too involved ...

**Comment by objarni** [comment] 2013-09-27 18:24
_BUMP_. Has this been fixed? What do you think of my feature request: cleanup on paste (replace double spaces with single spaces. And if you _really_ want the double-space-in-paste (I can think of 1 case of possibly 1000nds for my part since I started using etherpad 2009) for some odd reason, under "Pad options" a new tickbox [Remove double spaces on paste], which is ticked by default.

**Comment by JohnMcLear** [comment] 2013-09-27 18:33
We're not maintaining this repo, https://github.com/ether/etherpad-lite is where we're working now.

If you really wanna use the old Etherpad then I suggest forking and maintaining yourself alternatively have a chat with me and I can see if I can get an okay to make you an admin this repo.

If I was you I'd start using the latest version of Etherpad.

**Comment by objarni** [comment] 2013-09-27 18:43
Thank you John. I will try and reproduce this bug in an etherpad lite site first of all...

**Comment by objarni** [comment] 2013-09-27 18:45
Reproduced in this etherpad lite*: https://piratepad.ca/p/doublespacetest
- wow it looks a lot better than "old" etherpad! the whole sidebar/chat thing is much less intrusive, and the fixed width is gone...

**Comment by JohnMcLear** [comment] 2013-09-27 18:50
Hah.

Create an issue on github.com/etherpad/etherpad-lite for the import issue, will prolly get fixed asap

**Comment by objarni** [comment] 2013-09-27 18:54
Import issue? It's a paste issue. Even pasting within the same pad (old or new). But will add issue and reproduction steps to the lite github tracker! Thanks!

**Comment by JohnMcLear** [comment] 2013-09-27 18:55
paste issue then :) thanks

**Comment by objarni** [comment] 2013-09-27 19:08
^^

Issue reported: https://github.com/ether/etherpad-lite/issues/1910

**Comment by JohnMcLear** [comment] 2014-03-15 01:26
Fixed in etherpad lite

**Closed as completed by JohnMcLear** 2014-03-15 01:26 UTC
Labels: Editor, Bugs
