### ISSUE TITLE
Debian Startscript, update location of installation

### ISSUE THREAD

**Issue by pajoma** [ether/pad#195] opened 2010-11-15 14:37 UTC
Etherpad is by default installed into /usr/share/etherpad, the start script (etc/init.d/etherpad points to /usr/local/etherpad

**Comment by pierinz** [comment] 2011-01-13 00:06
I can confirm this issue. The latest package retrieved from repository is still broken.

**Comment by brother** [comment] 2011-02-10 00:08
until someone get their arm out of their ass and builds a new package:

sed ”s/local/share/” /etc/init.d/etherpad > /tmp/newinit
cp /etc/init.d/etherpad /etc/init.d/etherpad.orig
cat /tmp/newinit > /etc/init.d/etherpad
rm /tmp/newinit

like this in the debian package:

brother ~/tmp/etherpad (master)$ cat initd.patch 
diff --git a/data/etc/init.d/etherpad b/data/etc/init.d/etherpad
index 6b5af89..8176b41 100755
--- a/data/etc/init.d/etherpad
+++ b/data/etc/init.d/etherpad
@@ -47,7 +47,7 @@
 PATH=/sbin:/usr/sbin:/bin:/usr/bin
 DESC="Collaborative real-time editor"
 NAME="etherpad"
-DAEMON_BASE="/usr/local/etherpad"
+DAEMON_BASE="/usr/share/etherpad"
 DAEMON=$DAEMON_BASE/bin/run.sh
 DAEMON_ARGS=""
 PIDFILE=/var/run/$NAME.pid

**Comment by aog2000a** [comment] 2011-03-10 22:00
Hi,

replacing s/local/share/  helps but the right fix should also include the following:
- loading the /etc/default/etherpad file should be done _before_ the test for availability of the daemon, otherwise modifying the variable DAEMON 
  will have no effect, the script will exit immediately!

Thanks.
 Patch below (sorry the formatting gets lost)

 --- ../init.d/etherpad  2011-03-08 19:01:12.807577859 +0100
 +++ ../init.d/etherpad.orig     2011-03-08 18:58:37.887577857 +0100
 @@ -54,13 +54,12 @@
  SCRIPTNAME=/etc/init.d/$NAME
  OOFFICE_LOG="/var/log/etherpad/ooffice.log"

 -## This must be read before the next check
 -# Read configuration variable file if it is present
 -[ -r /etc/default/$NAME ] && . /etc/default/$NAME
 -
  # Exit if the package is not installed
  [ -x "$DAEMON" ] || exit 0

 +# Read configuration variable file if it is present
 +[ -r /etc/default/$NAME ] && . /etc/default/$NAME
 +
  # Load the VERBOSE setting and other rcS variables
  [ -f /etc/default/rcS ] && . /etc/default/rcS

**Comment by redhog** [comment] 2011-05-13 08:18
There seems to be a (partial) fix here
https://github.com/dekkers/pad/commit/c200ca989d5ca7a850a3d15495df8d5abb764e3f
by @dekkers
Does that solve the issue - that is, should I just merge that commit and close this, or is there more to do on this?

**Comment by dekkers** [comment] 2011-05-15 09:49
It resolves the issue reported by the bug submitter. With this patch the daemon starts correctly. The issue reported by aog2000a is a different issue and not really a problem IMHO. If the debian package is installed, you already know where the DAEMON is, no need to change it in a configuration file. If you look at other init scripts from Debian packages they usually also check whether the DAEMON is available before including the /etc/default/package config file.

**Comment by redhog** [comment] 2011-05-15 19:53
Any comments @aog2000a? Unless you have a good argument to counter @dekkers I guess I'm gonna close this issue...

**Comment by aog2000a** [comment] 2011-05-17 05:11
Hi dekkers, redhog, thanks for the DAEMON_BASE fix!
Well, i probably didn't explain my other issue well enough (and my patch seems to have original and modified files in the wrong order!). Also now, with the fixed DAEMON_BASE path, it is arguably not important anymore, but my point was:
- in /etc/init.d/etherpad  you currently have
              \* check if "$DAEMON" exists, else exit
              \* source /etc/default/etherpad if it exists
  in that order.

But that implies you cannot modify the variable $DAEMON in /etc/default, it's just hardcoded in the init script at the moment.  If you would put the checks in the opposite order:
                \* source /etc/default/etherpad if it exists
                \* check if "$DAEMON" exists, else exit
then you could also modify $DAEMON in /etc/default/etherpad.  This was relevant before when DAEMON was wrong, not not anymore.
So your choice. The change wouldn't hurt nor help much.... ;-)

**Comment by redhog** [comment] 2011-05-17 19:09
Well then I'll close the issue. If you feel like sending in a patch I'll happily apply it, but I won't spend any time fixing this myself :P

**Closed as completed** 2011-05-17 19:09 UTC
Labels: Install, Bugs, Patch included

**Comment by aog2000a** [comment] 2011-05-17 19:28
Hi,

> Well then I'll close the issue. If you feel like sending in a patch I'll
> happily apply it, but I won't spend any time fixing this myself :P

No problem, well the patch is in the bug comment (just reversed orig-new files)
but as i said i think now it is not relevant anymore, as the package is 
supplied with the right executable path.

Would only help if somebody wants to "misuse" the /etc/default/etherpad file 
for using(testing for instance) another executable instead of the one provided 
in the package... kind of misusing the package anyways.

Thanks, cheers, Ariel
